;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="State.Continue",NewTagName="State.Green")
+GameplayTagRedirects=(OldTagName="State.Prepare",NewTagName="State.Yellow")
+GameplayTagRedirects=(OldTagName="State.Stop",NewTagName="State.Red")
+GameplayTagRedirects=(OldTagName="Activities.CrossPath.Prepare",NewTagName="Activities.CrossPath.Aware")
+GameplayTagList=(Tag="Activities.CrossPath",DevComment="")
+GameplayTagList=(Tag="Activities.CrossPath.Aware",DevComment="")
+GameplayTagList=(Tag="Activities.CrossPath.Cross",DevComment="")
+GameplayTagList=(Tag="Activities.CrossPath.Wait",DevComment="")
+GameplayTagList=(Tag="Agents.Pedestrian",DevComment="")
+GameplayTagList=(Tag="State.Green",DevComment="")
+GameplayTagList=(Tag="State.Red",DevComment="")
+GameplayTagList=(Tag="State.SetupTime",DevComment="")
+GameplayTagList=(Tag="State.Yellow",DevComment="")

